version: '3'
services:
  mysql:
    image: mysql/mysql-server:8.0.23
    platform: linux/amd64
    container_name: lepus-app-template
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 53306:3306
    volumes:
      - ./database/mysql_data:/docker-entrypoint-initdb.d
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
  mysql2:
    image: mysql/mysql-server:8.0.23
    platform: linux/amd64
    container_name: lepus-app-template-replication
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 63306:3306
    volumes:
      - ./database/mysql_data:/docker-entrypoint-initdb.d
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf